tag_specification:
  name: '4.3'
  namespace: ocp
build_root:
  project_image:
    dockerfile_path: openshift/ci-operator/build-image/Dockerfile
binary_build_commands: make install
tests:
- as: e2e-aws-ocp-43
  commands: "make test-e2e"
  openshift_installer_src:
    cluster_profile: aws
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
