base_images:
  base:
    cluster: https://api.ci.openshift.org
    name: "4.3"
    namespace: ocp
    tag: base
  knative-serving-src:
    cluster: https://api.ci.openshift.org
    name: pipeline
    namespace: ci-op-r4wps7hl
    tag: knative-serving-src
  cli:
    cluster: https://api.ci.openshift.org
    name: "4.3"
    namespace: ocp
    tag: cli
build_root:
  project_image:
    dockerfile_path: openshift/ci-operator/build-image/Dockerfile
images:
- dockerfile_path: openshift/ci-operator/source-image/Dockerfile
  from: src
  inputs:
    cli:
      paths:
      - destination_dir: .
        source_path: /usr/bin/oc
  to: knative-serving-src
- context_dir: serving/ingress
  from: base
  to: knative-openshift-ingress
- context_dir: knative-operator
  from: base
  to: knative-operator
promotion:
  name: openshift-serverless-v1.7.0
  namespace: openshift
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tag_specification:
  cluster: https://api.ci.openshift.org
  name: "4.3"
  namespace: ocp
tests:
- as: e2e-aws-ocp-43
  steps:
    pre:
    - ref: ipi-conf
    - chain: ipi-install
    test:
    - ref:
        as: serverless-operator-e2e-test
        from: serverless-operator-src
        commands: make test-e2e
        documentation: |-
          The Serverless Operator E2E tests.
    - ref: knative-serving-e2e-test
    post:
    - chain: ipi-deprovision

commands: make test-e2e
  openshift_installer_src:
    cluster_profile: aws
- as: e2e-aws-ocp-43-continuous
  commands: make test-e2e
  cron: 0 */6 * * *
  openshift_installer_src:
    cluster_profile: aws
- as: upgrade-tests-aws-ocp-43
  commands: make test-upgrade
  openshift_installer_src:
    cluster_profile: aws
zz_generated_metadata:
  branch: release-1.7
  org: openshift-knative
  repo: serverless-operator
  variant: "4.3"
