base_images:
  base:
    cluster: https://api.ci.openshift.org
    name: "4.3"
    namespace: ocp
    tag: base
  knative-serving-src:
    cluster: https://api.ci.openshift.org
    name: pipeline
    namespace: ci-op-vkdxs923
    tag: knative-serving-src
  cli:
    cluster: https://api.ci.openshift.org
    name: "4.3"
    namespace: ocp
    tag: cli
build_root:
  project_image:
    dockerfile_path: openshift/ci-operator/build-image/Dockerfile
canonical_go_repository: github.com/openshift-knative/serverless-operator
images:
- context_dir: openshift/ci-operator/source-image
  from: src
  inputs:
    cli:
      paths:
      - destination_dir: .
        source_path: /usr/bin/oc
  to: serverless-operator-src
- context_dir: serving/ingress
  from: base
  to: knative-openshift-ingress
- context_dir: knative-operator
  from: base
  to: knative-operator
promotion:
  name: openshift-serverless-nightly
  namespace: openshift
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tag_specification:
  cluster: https://api.ci.openshift.org
  name: "4.3"
  namespace: ocp
tests:
- as: e2e-aws-ocp-43
  steps:
    cluster_profile: aws
    pre:
    - chain: ipi-aws-pre
    test:
    - as: serverless-operator-e2e-test
      from: serverless-operator-src
      commands: make test-e2e
      resources:
        requests:
          cpu: 500m
          memory: 500Mi
        limits:
          memory: 4Gi
      documentation: |-
        The Serverless Operator E2E tests.
    - as: knative-serving-e2e-test
      from: knative-serving-src
      commands: make TEST_IMAGE_TEMPLATE=registry.svc.ci.openshift.org/openshift/knative-v0.13.2:knative-serving-test-{{.Name}} test-e2e-no-install
      resources:
        requests:
          cpu: 500m
          memory: 500Mi
        limits:
          memory: 4Gi
      documentation: |-
        The Knative Serving E2E and Conformance tests.
    post:
    - chain: ipi-aws-post
- as: e2e-aws-ocp-43-continuous
  commands: make test-e2e
  cron: 0 */6 * * *
  openshift_installer_src:
    cluster_profile: aws
- as: upgrade-tests-aws-ocp-43
  commands: make test-upgrade
  openshift_installer_src:
    cluster_profile: aws
zz_generated_metadata:
  branch: steps_ci_operator_master
  org: mgencur
  repo: serverless-operator
  variant: "4.3"
